name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'

    - name: Install dependencies
      run: npm install
      working-directory: ./node-app

    - name: Run tests
      run: npm test
      working-directory: ./node-app

    - name: Stop existing Node.js app
      run: |
        if pgrep -f "node server.js"; then
          pkill -f "node server.js"
        fi
      shell: bash

    - name: Start Node.js app in background
      run: |
        nohup npm start --prefix ./node-app &
      shell: bash
